### ISSUE TITLE
在哪里可以找到2018版本的论文？

### ISSUE THREAD

**Issue by Dorismz** [chaoma99/lct-tracker#8]
因为想要用c++实现，所以需要看一下论文自己码代码,但是哪里可以看见论文呢？还有2018的链接是不是有问题啊，打开不了

**Comment by BossBobxuan** [comment]
Ma C, Huang J B, Yang X, et al. Adaptive Correlation Filters with Long-Term and Short-Term Memory for Object Tracking[J]. International Journal of Computer Vision, 2017(2):1-26.
